name: AppArchitecture
targets:
  AppArchitecture:
    type: application
    platform: iOS
    deploymentTarget: "9.0"
    sources: [AppArchitecture]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: studio.techpro.example.ios
      configs:
        Debug:
          debug
        Release:
          release
    dependencies:
      - carthage: RCRealm
      - carthage: RCKit 
      - carthage: Realm
      - carthage: RealmSwift
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: Swinject
